"""add_enabled_field_to_device

Revision ID: 257010976e6d
Revises: 
Create Date: 2025-11-27 11:28:08.887545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257010976e6d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('enabled', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_device_enabled'), 'device', ['enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_enabled'), table_name='device')
    op.drop_column('device', 'enabled')
    # ### end Alembic commands ###
